# Generated by Django 3.1.3 on 2020-12-18 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(error_messages={'unique': 'El producto con este SKU ya existe'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El SKU que ingresas no es correcto, debe de seguir la nomenclatura XX-###-### .', regex='[A-Z]{2}-[\\d]{3}-[\\d]{3}\\Z')])),
                ('description', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='categories.Categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
